

version: '3'

services:
    user-db:
      image: gcr.io/vmwarecloudadvocacy/acmeshop-user-db:latest
      hostname: user-db
      environment:
        - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        - MONGO_INITDB_ROOT_PASSWORD=secret
        - MONGO_INITDB_DATABASE=acmefit
      cap_add:
        - CHOWN
        - SETGID
        - SETUID
      tmpfs:
        - /tmp:rw,noexec,nosuid
    user-redis-db:
      image: bitnami/redis
      hostname: user-redis-db
      restart: always
      ports:
        - '6379:6379'
      environment:
        - REDIS_PASSWORD=secret
    user:
       image: gcr.io/vmwarecloudadvocacy/acmeshop-user:2.0.0
       hostname: users
       restart: always
       ports:
         - '8083:8083'
       cap_add:
           - NET_BIND_SERVICE
       environment:
           - USERS_DB_USERNAME=mongoadmin
           - USERS_DB_PASSWORD=secret
           - USERS_DB_HOST=user-db
           - USERS_DB_PORT=27017
           - USERS_PORT=8083
           - REDIS_HOST=user-redis-db
           - REDIS_PORT=6379
           - REDIS_PASSWORD=secret
           - JAEGER_AGENT_HOST=localhost
           - JAEGER_AGENT_PORT=6831
       depends_on:
           - user-redis-db
           - user-db
